// actionTypes.js
export const FETCH_HOTEL_BY_ID_REQUEST = 'FETCH_HOTEL_BY_ID_REQUEST';
export const FETCH_HOTEL_BY_ID_SUCCESS = 'FETCH_HOTEL_BY_ID_SUCCESS';
export const FETCH_HOTEL_BY_ID_FAILURE = 'FETCH_HOTEL_BY_ID_FAILURE';

export const SET_CURRENT_BOOKING_INFO = 'SET_CURRENT_BOOKING_INFO';
export const ADD_BOOKING_RESULT = 'ADD_BOOKING_RESULT';
export const SCROLL_TO_HOTELS = 'SCROLL_TO_HOTELS';
export const RESET_SCROLL = 'RESET_SCROLL'; 

